# Generated by Django 3.1.1 on 2020-10-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201003_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
    ]
