# Generated by Django 3.1.1 on 2020-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20201003_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.CharField(max_length=200),
        ),
    ]
