# Generated by Django 3.1.1 on 2020-10-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20201004_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categorys',
        ),
    ]
