# Generated by Django 3.1.1 on 2020-10-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20201009_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='category_product',
        ),
    ]
