# Generated by Django 3.1.1 on 2020-10-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20201009_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_product',
            field=models.ManyToManyField(blank=True, related_name='albums', to='search.Category'),
        ),
    ]
