# Generated by Django 3.1.1 on 2020-10-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20201009_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
    ]
