# Generated by Django 3.1.1 on 2020-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20201009_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='0', max_length=200, unique=True),
        ),
    ]
