# Generated by Django 3.1.1 on 2020-10-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20201009_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
