# Generated by Django 3.1.1 on 2020-10-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0016_auto_20201009_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('score', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.category')),
            ],
        ),
    ]
