# Generated by Django 3.1.1 on 2020-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_auto_20201009_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
