# Generated by Django 3.1.1 on 2020-10-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0020_auto_20201009_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('score', models.CharField(max_length=200, null=True)),
                ('img_url', models.URLField()),
                ('category_product', models.ManyToManyField(blank=True, related_name='Category', to='search.Category')),
            ],
        ),
    ]
