# Generated by Django 3.1.1 on 2020-10-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
    ]
