# Generated by Django 3.1.1 on 2020-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_product_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(max_length=200, null=True, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='favorites', to='search.Product')),
            ],
        ),
    ]
